name: Build/Deploy atcoder-rs-base

on:
  push:
    paths:
      - "atcoder-rs-base/*"
      - ".github/workflows/build-atcoder-rs-base.yml"
    branches: [main]
  pull_request:
    paths:
      - "atcoder-rs-base/*"
      - ".github/workflows/build-atcoder-rs-base.yml"
    branches: [main]
  schedule:
    - cron: "0 1 * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: atcoder-rs-base
          push: true
          tags: masinc/atcoder-rs-base:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
