name: Build/Deploy atcoder-rs-redis

on:
  push:
    branches: [main]
    paths:
      - "atcoder-rs/redis/**"
      - "docker-composer-builder.yml"
      - ".github/workflows/build-atcoder-rs-redis.yml"
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: PreBuild
        run: |
          docker-compose -f docker-composer-builder.yml up -d
          docker-compose -f docker-composer-builder.yml run cache-builder /root/start.sh
          docker-compose -f docker-composer-builder.yml down
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: atcoder-rs-redis
          push: true
          tags: masinc/atcoder-rs-redis:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
